- name: deploy and run redmine docker container
  hosts: all
  become: yes
  vars_files:
    - group_vars/all/vars.yaml
  tasks:
    - name: generate .env file from template
      template:
        src: templates/.env.j2
        dest: .env

    - name: pull redmine docker image
      community.docker.docker_image:
        name: redmine:latest
        source: pull

    - name: run redmine docker container
      community.docker.docker_container:
        name: redmine_container
        image: redmine:5.1.1
        ports:
          - "{{ REDMINE_PORT }}:3000"
        restart_policy: always
      register: redmine_container

    - name: verify redmine container is running
      assert:
        that:
          - redmine_container is defined
          - redmine_container.container.State.Running
        fail_msg: "Redmine container is not running"
        success_msg: "Redmine container is running"

    - name: Debugging output
      debug:
        var: redmine_container
      when: redmine_container is failed