- name: setup the application servers
  hosts: all
  become: yes
  vars_files:
    - group_vars/hosts.yml
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
            state: latest
    - role: geerlingguy.docker