- name: setup the application servers
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
            state: latest

- name: install datadog agent on servers
  hosts: webservers
  become: yes
  vars:
    datadog_api_key: "{{ DATADOG_API_KEY }}"
    datadog_site: "{{ DATADOG_SITE }}"
    datadog_apm_instrumentation_enabled: "all"
  tasks:
    - name: import the datadog agent role from the datadog collection
      import_role:
        name: datadog.dd.agent

    - name: configure http_check
      template:
        src: http-check/config.j2
        dest: /etc/datadog-agent/conf.d/http_check.yaml
      notify: restart datadog agent

  handlers:
    - name: restart datadog agent
      ansible.builtin.service:
        name: datadog-agent
        state: restarted